<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>DumpDetective.Reporting</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Templates\report.html" />
    <EmbeddedResource Include="Templates\report.css" />
    <EmbeddedResource Include="Templates\report.js" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DumpDetective.Core\DumpDetective.Core.csproj" />
    <ProjectReference Include="..\DumpDetective.Analysis\DumpDetective.Analysis.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DumpDetective.Cli" />
    <InternalsVisibleTo Include="DumpDetective.Tests" />
    <InternalsVisibleTo Include="BenchmarkSuite1" />
  </ItemGroup>
</Project>
