<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>DumpDetective.Platform</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Hashing" Version="10.0.9" />
    <ProjectReference Include="..\DumpDetective.Sdk\DumpDetective.Sdk.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DumpDetective.Analysis" />
    <InternalsVisibleTo Include="DumpDetective.Tests" />
  </ItemGroup>

</Project>
