<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>DumpDetective.Analysis</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Configuration\**" />
    <EmbeddedResource Remove="Configuration\**" />
    <None Remove="Configuration\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.IO.Hashing" Version="10.0.9" />
    <ProjectReference Include="..\DumpDetective.Core\DumpDetective.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="DumpDetective.Cli" />
    <InternalsVisibleTo Include="DumpDetective.Reporting" />
    <InternalsVisibleTo Include="DumpDetective.Tests" />
    <InternalsVisibleTo Include="BenchmarkSuite1" />
    <InternalsVisibleTo Include="ProfileRootEnumeration" />
  </ItemGroup>
</Project>
